### ISSUE TITLE
USER STORY -07-from the perspective of employability team - wiil be added by KAM

### ISSUE THREAD

**Issue by EABarton123** [EABarton123/NW5-group-3-Road-to-Tech#6]
1. Add user story from the perspective of employability team on miro
2. Design in figma ( if possible)

**Comment by Adibab** [comment]
![Image](https://user-images.githubusercontent.com/92828540/224177562-adfd26b4-1a52-4e81-85e8-3f1f37b218d9.png)

**Comment by Adibab** [comment]
![Image](https://user-images.githubusercontent.com/92828540/224177646-165e1af7-fb05-4c9f-a55c-5ac89517caea.png)
