### ISSUE TITLE
start react for page 1 (homepage)

### ISSUE THREAD

**Issue by EABarton123** [EABarton123/NW5-group-3-Road-to-Tech#7]
we need to break down this problem, how will we start? what tasks need to be completed first to get the page up and running. HTML/ react?

Once we have a clear task we need to create an issue.

**Comment by Adibab** [comment]
On 10/03 notes by Adiba
NOTES FROM THE MEETING
User story - page 1 start HTML/ CSS/ react concentrating on Nav bar and footer: Kam & Emily;
page 6/7/8 - Adiba;
page 2/3/4- same requirements: Sandra;
page 10 start HTML/ CSS/ react (without nav bar or footer): refik;
