### ISSUE TITLE
USER STORY-08-CREATE A PROFILE / UPLOAD RESUME ( OPTIONAL FOR 09/03)(08/03/23) 

### ISSUE THREAD

**Issue by Adibab** [EABarton123/NW5-group-3-Road-to-Tech#8]
As a - Graduate,
I Want - to be able to create a profile and upload my resume,

So That - employers can find me and I can apply for jobs more easily.

Acceptance Criteria
A/C 1:
A/C 2:
Implementation Notes
Note 1:
Note 2:
## Checklist:

- [x] I have defined the user story
- [x] I have defined some acceptance criteria
- [x] I have included any implementation notes
- [x] I have included all relevant links

**Comment by Sandra-Duarte** [comment]
Job Upload process -admin

As an employment team member, I want to be able to create a job posting on the website, with a template of required informatio.

Job required Template-

Constraints
Number of Git commits: Text Box
CodeWar Kata level: Drop down
CodeWar points: Text Box
Codility Test points: Text Box

Job Title: Text Box]
Job Category: (Drop-down list of categories]
Job Type: [Drop-down list of job types]
Salary Range: [Text Box]
Job Description: (Text Box]
Responsibilities: [Text Box]
Requirements: [Text Box
Application Deadline: (Calendar)
Contact Information:
Name: [Text Box]
﻿﻿Email: [Text Box]
﻿﻿Phone: [Text Box]

Company Information:
• Name: Text Box
 Website: [Text Box]
 Logo: (File Upload)
Preview and Publich button

Number of students can apply:
